### PR TITLE
Some cleanup for better IDE readability and inspection.

### PR DESCRIPTION
**Pull request by shehi**
@hakanersu : I cleared SASS files a bit by removing some repeating and overriding properties. Additionally optimized ```padding``` a little and added fallback ```sans-serif``` to ```font-family``` properties..

### CODE REVIEW

**Comment by hakanersu** [comment]
Thank you for your contribution.

**Comment by shehi** [comment]
You are welcome. I use this package, but IDE gives me a headache, so in order to get rid of SCSS errors, I had to cleanup and send this patch :) Enjoy, thanks and have a good day!

**Comment by shehi** [comment]
Oh and please be advised that I didn't recreate CSS files (if they need to), so they are still in the original shape. You might want to re-compile them (in case that's how you created them).

**Comment by hakanersu** [comment]
Right :) i totally forget about that ill push with some other changes.

**Comment by shehi** [comment]
Will there be a SASS/SCSS support? I noticed you had a new release recently, but guess no SASS in them so far.

**Comment by shehi** [comment]
My bad re the previous post of mine (deleted it, posting here in case you got email from Github): I mixed up your project with some other :) Ignore that email if you received it.

**Pull request merged**
